/*
 * This Java source file was generated by the Gradle 'init' task.
 */
 package bi.project;

import ru.yandex.qatools.ashot.AShot;
import ru.yandex.qatools.ashot.Screenshot;
import ru.yandex.qatools.ashot.shooting.ShootingStrategies;
import javax.imageio.ImageIO;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.plaf.synth.SynthOptionPaneUI;

import org.apache.hc.core5.util.Args;
import org.checkerframework.checker.units.qual.s;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import io.github.bonigarcia.wdm.WebDriverManager;

public class App {
    public static ChromeDriver createDriver(){
        //TODO Create a new chrome Driver and Return the same
        WebDriverManager.chromedriver().setup();

        ChromeDriver driver;
        driver = new ChromeDriver();
        
        return driver;
    }
    public static void printQKartLoadingtime(ChromeDriver driver){
        //TODO Navigate to home page of QKart and verify the time taken for the page to load
       // Create a new variable that would hold the current timestamp Eg. start
       long start = System.currentTimeMillis();
       // Navigate to the QKart home page by using driver.get() method
        driver.get("https://crio-qkart-frontend-qa.vercel.app");
        // Create another variable that would hold the current timestamp Eg. end
        long end = System.currentTimeMillis();
        // Find the difference between the two timestamps i.e end - start
        long time = (end - start)/1000;
        // Print the time taken in seconds in this format - Time taken to load QKart Page: 3 seconds
        System.out.println("Time taken to load QKart Page: "+ time +" seconds");
        
    }
 
    public static void captureFullPageScreenshot(ChromeDriver driver) throws IOException{
        //TODO: Capture the full page screenshot
        //Save the file with a unique name
        // Print the path of the file
        // Create a variable that holds the current timestamp. This will be used as a file name for uniquely naming the files
        String timestamp = new SimpleDateFormat("yyyyMMddHHmmss").format(new Date());
       // Navigating to the QKart home page by using driver.get() method
       driver.get("https://crio-qkart-frontend-qa.vercel.app");
       // Create an instance of AShot object
       AShot ashot = new AShot();
       // Capture a full page screenshot
       Screenshot screenshot = ashot.takeScreenshot(driver);
       // Save the captured file with a unique name ( file name we generated in step 1)
       String fileName = "ScreenShot" + timestamp + ".png";
       ImageIO.write(screenshot.getImage(), "PNG", new File(fileName));
        // Print out the capture screenshot name
        System.out.println("Captured screenshot saved as: " + fileName);
    }
 
    public static void GetProductImageandURL(ChromeDriver driver, String productName) throws InterruptedException{
        //TODO: Given the product name, print the price of the project and the url of the image
        // Navigate to QKart Page
        driver.get("https://crio-qkart-frontend-qa.vercel.app");
        // Wait for the products to load
        WebDriverWait wait = new WebDriverWait(driver,30);
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("search")));
        // Search for the element with given input text (received from args) using dynamic Xpath.  Eg. //<tag>[text()=’productname’]
        WebElement element = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//*[text()='" + productName + "']")));
        // Find the price value of the above element
        WebElement priceElement = element.findElement(By.xpath("//*[text()='" + productName + "']/..//p[contains(text(),'$')]"));
        String price = priceElement.getText();
        // Find the image URL of the above element
        WebElement imageElement = element.findElement(By.xpath("//*[text()='" + productName + "']/../..//img"));
        // Use getAttribute("src"); to get the URL of the image (as the <img> tag has the image URL in its src attribute)
        String imageUrl = imageElement.getAttribute("src");
        // Print the price and image url of the element
        System.out.println("Price of the product is : "+price);
        System.out.println("url of the product image is : " + imageUrl);
        
    }


    public static void main(String[] args) {
        ChromeDriver driver = createDriver();
       String input = String.join(" ", args );
       try{

           printQKartLoadingtime(driver);

           captureFullPageScreenshot(driver);
          
           GetProductImageandURL(driver,input);
          
       }catch(Exception e)
       {
           System.out.println(e.getMessage());
       }finally{
           driver.quit();
       }
   }
    }
