/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.io.IOException;
 import java.net.MalformedURLException;

import org.checkerframework.checker.units.qual.A;


public class App {
    public void getGreeting() throws InterruptedException, IOException {
       // TestCases tests = new TestCases(); // Initialize your test class
       //TODO: call your test case functions one after other here
       // tests.testCase01();
        //END Tests
        // tests.endTest(); // End your test by clearning connections and closing browser

// uncomment for Search_Amazon.java

        // Search_Amazon search = new Search_Amazon();
        // search.searchAmazon();
        // search.endTest();

// uncomment for Count_Hyperlinks.java

        // Count_Hyperlinks linkscount = new Count_Hyperlinks();
        // linkscount.countHyperlinks();
        // linkscount.endTest();

// uncomment for LinkedIn_Post.java        
 
        // LinkedIn_Post linkedinpost = new LinkedIn_Post();
        // linkedinpost.linkedinPost();
        // linkedinpost.endTest();

// uncomment for Image_Url.java        

        // Image_Url imageurl = new Image_Url();
        // imageurl.imageURL();
        // imageurl.endTest();

// uncomment for Nested_Frames.java

        // Nested_Frames frames = new Nested_Frames();
        // frames.nestedFrames();
        // frames.endTest();

// uncomment for LinkedIn_ImagePost.java

        // LinkedIn_ImagePost imgpost = new LinkedIn_ImagePost();
        // imgpost.linkedIn_ImgPost();
        // imgpost.endTest();

// uncomment for Imdb_Ratings.java

        // Imdb_Ratings imdbRatings = new Imdb_Ratings();
        // imdbRatings.imdb_Ratings();
        // imdbRatings.endTest();

// uncomment for Google_NameLinks.java

        // Google_NameLinks nameLinks = new Google_NameLinks();
        // nameLinks.google_NameLinks();
        // nameLinks.endTest();
        
// uncomment for Window_Handles.java

        Window_Handles windowHandles = new Window_Handles();
        windowHandles.window_Handles();
        windowHandles.endTest();

// uncomment for Alert_Prompt.java

        // Alert_Prompt alertPrompt = new Alert_Prompt();
        // alertPrompt.alert_Prompt();
        // alertPrompt.endTest();

       
        
        
        
        
       


      
        
        
       
        
    }

    public static void main(String[] args) throws InterruptedException, IOException {
        new App().getGreeting();
        
    }
}
